import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import { getServerSession } from "next-auth";
import { AuthProvider } from "./Providers";
import { authOptions } from "../app/api/auth/[...nextauth]/route";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Zaraee.pk',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar session={session}/>
        <AuthProvider>{children}</AuthProvider>
        <Footer/>
        
      </body>
    </html>
  )
}
